version: 1.0.{build}

image: Ubuntu

environment:
  matrix:
    - nodejs_version: "12"

platform:
  - x86
  - x64

install:
  # - ps: Install-Product node $env:nodejs_version
  # - sh: sudo apt-get update
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) $env:PLATFORM
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

build: off